/*配置路由*/
let app=angular.module("app",['ui.router']);
    app.config(['$stateProvider','$urlRouterProvider' ,function($stateProvider,$urlRouterProvider){
        $urlRouterProvider.otherwise("certificate");//默认跳到企业认证
        $stateProvider
            /*离职评价模块*/
            .state('search',{
                url:"/search",
                templateUrl:'leave/search.html',//离职评价查询
                controller:'search',
            })
            .state('leaveReport',{
                url:'/leaveReport/:userId/:reportFlag',
                templateUrl:'leave/leaveReport.html',//；离职报告
                controller:'leaveReport'
            })
            /*.state('ablity',{
                url:'/ablity',
                templateUrl:'leave/ablity.html',//能力评价
                controller:'ablity'
            })*/
            .state('uploadLeave',{
                url:'/uploadLeave',
                templateUrl:'leave/uploadLeave.html',//上传离职评价
                controller:'uploadLeave'
            })

            .state('competency',{
                url:'/competency',
                templateUrl:'leave/competency.html',//；胜任力模型评测（能力评价）
                controller:'competency'
            })
            .state('myUpload',{
                url:"/myUpload",
                templateUrl:'leave/myUpload.html',//我的上传
                controller:'myUpload',
            })
            .state('updateReport',{
                url:"/updateReport",
                templateUrl:'leave/updateReport.html',//修改离职报告
                controller:'updateReport',
            })
            .state('searchRecord',{
                url:'/searchRecord',
                templateUrl:'leave/searchRecord.html',//查询记录
                controller:'searchRecord'
            })


            /*账号管理模块*/
            .state('certificate',{
                url:"/certificate",
                templateUrl:'account/certificate.html',//企业认证
                controller:'certificate',
            })
            //账号安全
            .state('account',{
                url:'/account',
                templateUrl:'account/account.html',//账号
                controller:'account'
            })
                .state('updateMobile',{
                    url:'/updateMobile',
                    templateUrl:'account/updateMobile.html',//修改手机号
                    controller:'updateMobile'
                })
                .state('bindEmail',{
                    url:'/bindEmail',
                    templateUrl:'account/bindEmail.html',//绑定邮箱
                    controller:'bindEmail'
                })
                .state('updatePsd',{
                    url:'/updatePsd',
                    templateUrl:'account/updatePsd.html',//修改密码
                    controller:'updatePsd'
                })
            //企业资料
            .state('company',{
                url:"/company",
                templateUrl:'account/company.html',//企业信息
                controller:'company'
            })
            .state('industry',{
                url:'/industry',
                templateUrl:'account/industry.html',//所属行业
                controller:'industry'
            })
            .state('scale',{
                url:'/scale',
                templateUrl:'account/scale.html',//公司规模
                controller:'scale'
            })
            .state('address',{
                url:'/address',
                templateUrl:'account/address.html',//修改地址
                controller:'address'
            })



    }]);
